// Mocks generated by Mockito 5.4.6 from annotations
// in algo_lab/test/features/home/providers/home_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:algo_lab/features/home/domain/entities/algorithm_entity.dart'
    as _i5;
import 'package:algo_lab/features/home/domain/repository/algorithm_repository.dart'
    as _i2;
import 'package:algo_lab/features/home/domain/usecases/get_algorithms_usecase.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAlgorithmRepository_0 extends _i1.SmartFake
    implements _i2.AlgorithmRepository {
  _FakeAlgorithmRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetAlgorithmsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAlgorithmsUseCase extends _i1.Mock
    implements _i3.GetAlgorithmsUseCase {
  MockGetAlgorithmsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AlgorithmRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAlgorithmRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AlgorithmRepository);

  @override
  _i4.Future<List<_i5.AlgorithmEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<List<_i5.AlgorithmEntity>>.value(
              <_i5.AlgorithmEntity>[],
            ),
          )
          as _i4.Future<List<_i5.AlgorithmEntity>>);
}
