// Mocks generated by Mockito 5.4.6 from annotations
// in algo_lab/test/features/cryptography_lab/presentation/provider/rsa_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:algo_lab/features/cryptography_lab/domain/entities/rsa_entity.dart'
    as _i2;
import 'package:algo_lab/features/cryptography_lab/domain/usecases/rsa_usecase.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRSAKeyPair_0 extends _i1.SmartFake implements _i2.RSAKeyPair {
  _FakeRSAKeyPair_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RSAUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRSAUseCase extends _i1.Mock implements _i3.RSAUseCase {
  MockRSAUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RSAKeyPair generateKeyPair() =>
      (super.noSuchMethod(
            Invocation.method(#generateKeyPair, []),
            returnValue: _FakeRSAKeyPair_0(
              this,
              Invocation.method(#generateKeyPair, []),
            ),
          )
          as _i2.RSAKeyPair);

  @override
  BigInt encrypt(BigInt? m, BigInt? e, BigInt? n) =>
      (super.noSuchMethod(
            Invocation.method(#encrypt, [m, e, n]),
            returnValue: _i4.dummyValue<BigInt>(
              this,
              Invocation.method(#encrypt, [m, e, n]),
            ),
          )
          as BigInt);

  @override
  BigInt decrypt(BigInt? c, BigInt? d, BigInt? n) =>
      (super.noSuchMethod(
            Invocation.method(#decrypt, [c, d, n]),
            returnValue: _i4.dummyValue<BigInt>(
              this,
              Invocation.method(#decrypt, [c, d, n]),
            ),
          )
          as BigInt);
}
