// Mocks generated by Mockito 5.4.6 from annotations
// in algo_lab/test/features/pathfinding/presentation/provider/pathfinding_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:algo_lab/features/pathfinding/domain/entities/grid_node.dart'
    as _i4;
import 'package:algo_lab/features/pathfinding/domain/usecases/astar_usecase.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AStarUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAStarUseCase extends _i1.Mock implements _i2.AStarUseCase {
  MockAStarUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> findPath({
    required List<List<_i4.GridNode>>? grid,
    required _i4.GridNode? startNode,
    required _i4.GridNode? endNode,
    required dynamic Function(List<_i4.GridNode>, List<_i4.GridNode>)? onStep,
    required Duration? delay,
    bool? allowDiagonal = false,
    _i2.HeuristicType? heuristic = _i2.HeuristicType.manhattan,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findPath, [], {
              #grid: grid,
              #startNode: startNode,
              #endNode: endNode,
              #onStep: onStep,
              #delay: delay,
              #allowDiagonal: allowDiagonal,
              #heuristic: heuristic,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
