// Mocks generated by Mockito 5.4.6 from annotations
// in algo_lab/test/features/profile/domain/usecases/profile_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:algo_lab/features/profile/domain/entities/profile_entity.dart'
    as _i4;
import 'package:algo_lab/features/profile/domain/repository/profile_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i2.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ProfileEntity?> getProfile(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, [uid]),
            returnValue: _i3.Future<_i4.ProfileEntity?>.value(),
          )
          as _i3.Future<_i4.ProfileEntity?>);

  @override
  _i3.Future<void> updateProfile(_i4.ProfileEntity? profile) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [profile]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<_i4.ProfileEntity?> watchProfile(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#watchProfile, [uid]),
            returnValue: _i3.Stream<_i4.ProfileEntity?>.empty(),
          )
          as _i3.Stream<_i4.ProfileEntity?>);
}
